apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-payment-service
  labels: 
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: bookstore-payment-service
        image: iampavankalyan/bookstore-payment-service:1.0
        ports:
          - containerPort: 8001
        imagePullPolicy: Always
        env:
        - name: DT_CUSTOM_PROP
          value: "project=dt-orders service=payment-service"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  type: NodePort
  selector:
    app: payment
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
