apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-billing-service
  labels: 
    app: billing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
      - name: bookstore-billing-service
        image: iampavankalyan/bookstore-billing-service:1.0
        ports:
          - containerPort: 5001
        imagePullPolicy: Always
        env:
        - name: DT_CUSTOM_PROP
          value: "project=dt-orders service=billing-service"
---
apiVersion: v1
kind: Service
metadata:
  name: billing-service
  labels:
    app: billing-service
spec:
  type: NodePort
  selector:
    app: billing
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
