apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-account-service
  labels: 
    app: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: bookstore-account-service
        image: iampavankalyan/bookstore-account-service:1.0
        ports:
          - containerPort: 4001
        imagePullPolicy: Always
        env:
        - name: DT_CUSTOM_PROP
          value: "project=dt-orders service=account-service"
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  type: NodePort
  selector:
    app: account
  ports:
  - protocol: TCP
    port: 4001
    targetPort: 4001
