apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-order-service
  labels: 
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: bookstore-order-service
        image: iampavankalyan/bookstore-order-service:1.0
        ports:
          - containerPort: 7001
        imagePullPolicy: Always
        env:
        - name: DT_CUSTOM_PROP
          value: "project=dt-orders service=order-service"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  type: NodePort
  selector:
    app: order
  ports:
  - protocol: TCP
    port: 7001
    targetPort: 7001
