apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  labels:
    app: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end
        image: rajureddy98/book-store-ui:1.0
        ports:
          - containerPort: 3000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: front-end-service
  labels:
    app: front-end-service
spec:
  type: LoadBalancer
  selector:
    app: front-end
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
