apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-catalog-service
  labels: 
    app: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: bookstore-catalog-service
        image: iampavankalyan/bookstore-catalog-service:1.0
        imagePullPolicy: Always
        ports:
          - containerPort: 6001
        imagePullPolicy: Always
        env:
        - name: DT_CUSTOM_PROP
          value: "project=dt-orders service=catalog-service"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  type: NodePort
  selector:
    app: catalog
  ports:
  - protocol: TCP
    port: 6001
    targetPort: 6001
