apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-eureka-discovery-service
  labels:
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: bookstore-eureka-discovery-service
        image: iampavankalyan/bookstore-eureka-discovery-service:1.0
        ports:
          - containerPort: 8761
        env:
        - name: DT_CUSTOM_PROP
          value: "project=dt-orders service=eureka-service"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    app: eureka-service
spec:
  type: LoadBalancer
  selector:
    app: eureka
  ports:
  - protocol: TCP
    port: 8761
    targetPort: 8761
